### ISSUE TITLE
feat: behavior pack generators implement

### ISSUE THREAD

**Issue by NguyenDuck** [lancelotF/ModEx#7]
This issue is tracker for the implementation of behavior pack generators.

- [x] Animation Controller
- [x] Animation
- [x] Biome
- [x] Block
- [x] Camera Preset
- [x] Dialogue
- [x] Entity
- [x] Feature Rule
- [x] Feature
- [x] Function
- [x] Item
- [ ] #10
- [x] Loot Table
- [x] Recipe
- [x] Spawn Rule
- [x] Trading
- [ ] #9

**Comment by lancelotF** [comment]
Marking this as solved since most of the generators are now implemented.
Created new issues for the world gen and lightning generators
